server:
  port: 9002

spring:
  application:
    name: Note2
  datasource:
    username: root
    password: root@Luo115
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/note2?charactorEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai
mybatis:
  type-aliases-package: com/haha/note2/pojo
  mapper-locations: classpath:mapper/*Mapper.xml
